version : “3”
services :
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 9000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./core:/tmp/core
      - ./nav/build:/tmp/nav
      - ./footer/build:/tmp/footer
      - ./pages/build:/tmp/pages
